sudo: false
language: python
python:
  - "3.5"
  - "3.6"
cache:
  directories:
  - $HOME/.cache/pip
install: pip install tox coveralls wheel
script: tox
env:
  - TOXENV=py35
  - TOXENV=py36
after_success: coveralls
